services:
  # 1. Database Khusus BrainScan AI
  db:
    image: postgres:15-alpine
    container_name: brainscan-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passwordnabilaesd
      POSTGRES_DB: tumordb
    ports:
      - "5433:5432"
    volumes:
      - brainscan_postgres_data:/var/lib/postgresql/data

  # 2. Backend FastAPI & AI Khusus BrainScan AI
  fastapi-backend:
    image: backend-tumor-celery-worker:latest
    container_name: brainscan-backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./uploads:/app/uploads
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped

volumes:
  brainscan_postgres_data: